M48
; DRILL file {KiCad 7.0.0-da2b9df05c~163~ubuntu22.04.1} date Sun 19 Feb 2023 09:52:57 AM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-19T09:52:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0-da2b9df05c~163~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.000
%
G90
G05
T1
X125.0Y-88.0
T0
M30
